/**
 * Markdown exporter — converts generated briefs to a Notion-compatible
 * Markdown string and triggers a file download.
 */

import type { ContentBrief } from '@/types/database'
import type { Goal } from '@/types/database'

const FORMAT_LABELS: Record<string, string> = {
  IMAGE:          'Image',
  VIDEO:          'Video',
  CAROUSEL_ALBUM: 'Carousel',
}

function briefToMarkdown(brief: ContentBrief, index: number): string {
  return [
    `## ${index + 1}. ${brief.title}`,
    '',
    `**Format:** ${FORMAT_LABELS[brief.format] ?? brief.format}`,
    '',
    `**Hook**`,
    brief.hook,
    '',
    `**Structure**`,
    brief.structure,
    '',
    `**Caption draft**`,
    brief.captionDraft,
    '',
    `**Call to action:** ${brief.cta}`,
    '',
    `> *Rationale: ${brief.rationale}*`,
    '',
    '---',
    '',
  ].join('\n')
}

/** Build the complete Markdown document string */
export function buildMarkdown(briefs: ContentBrief[], goal: Goal): string {
  const goalLabel = goal === 'growth' ? 'Growth' : 'Leads & Sales'
  const dateStr = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric',
  })

  const header = [
    `# Content Briefs — ${goalLabel} — ${dateStr}`,
    '',
    `*Generated by Insta Insights · ${briefs.length} brief${briefs.length !== 1 ? 's' : ''}*`,
    '',
    '---',
    '',
  ].join('\n')

  return header + briefs.map((b, i) => briefToMarkdown(b, i)).join('')
}

/** Trigger a .md file download in the browser */
export function downloadMarkdown(briefs: ContentBrief[], goal: Goal): void {
  const content = buildMarkdown(briefs, goal)
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' })
  const url = URL.createObjectURL(blob)

  const a = document.createElement('a')
  a.href = url
  a.download = `insta-insights-briefs-${goal}-${Date.now()}.md`
  a.click()

  URL.revokeObjectURL(url)
}

/** Copy Notion-ready markdown to the clipboard */
export async function copyToClipboard(briefs: ContentBrief[], goal: Goal): Promise<void> {
  const content = buildMarkdown(briefs, goal)
  await navigator.clipboard.writeText(content)
}
